# Generated by Django 4.0.2 on 2022-02-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_created=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_in', to='cars.cars')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.clients')),
            ],
        ),
    ]
