# Generated by Django 4.0.2 on 2022-02-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='extended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExtendedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_from', models.DateField()),
                ('extended_to', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_form', to='orders.orders')),
            ],
        ),
    ]
